resources:
- name: tick-tock
  type: time
  source:
    interval: 1h

jobs:
- name: simple-job
  plan:
  - get: tick-tock
  - task: simple-task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: {repository: busybox}
      inputs:
      - name: tick-tock
      run:
        path: sh
        args:
        - -c
        - |
          until test -f /tmp/stop-waiting; do
            echo 'waiting for /tmp/stop-waiting to exist'
            sleep 1
          done

          echo done
  - put: tick-tock
