jobs:
- name: unit
  plan:
  - task: run
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      run:
        path: /bin/sh
        args:
        - -c
        - |
          echo plain-secret=((foo))
          echo nested-secret=((caz.baz))
