AllCops:
  TargetRubyVersion: 2.4

Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
