---
name: ((deployment_name))

releases:
- name: concourse((suite))
  version: ((concourse_release_version))
- name: bpm
  version: ((bpm_release_version))
- name: postgres
  version: ((postgres_release_version))

instance_groups:
- name: web
  instances: 1
  networks: [{name: test}]
  azs: [z1]
  vm_type: test
  stemcell: xenial
  jobs:
  - release: bpm
    name: bpm

  - release: concourse((suite))
    name: web
    properties:
      add_local_users:
        test: test
        guest: guest

      main_team:
        auth:
          local:
            users: [test]

      token_signing_key: ((token_signing_key))

      log_level: debug

      postgresql:
        database: &db-name atc
        role: &db-role
          name: atc
          password: dummy-password

      worker_gateway:
        log_level: debug
        host_key: ((tsa_host_key))
        token_signing_key: ((token_signing_key))
        authorized_keys: [((worker_key.public_key))]

- name: db
  instances: 1
  networks: [{name: test}]
  azs: [z1]
  # don't bother with persistent disk
  # persistent_disk: 10240
  vm_type: test
  stemcell: xenial
  jobs:
  - release: postgres
    name: postgres
    properties:
      databases:
        port: 5432
        databases:
        - name: *db-name
        roles:
        - *db-role

- name: worker
  instances: 1
  networks: [{name: test}]
  azs: [z1]
  vm_type: test
  stemcell: xenial
  jobs:
  - release: concourse((suite))
    name: worker
    properties:
      log_level: debug
      worker_gateway:
        worker_key: ((worker_key))
      baggageclaim:
        driver: overlay
      # prevent tests from hanging forever
      drain_timeout: 10m

variables:
- name: token_signing_key
  type: rsa
- name: tsa_host_key
  type: ssh
- name: worker_key
  type: ssh

stemcells:
- alias: xenial
  os: ubuntu-xenial
  version: ((stemcell_version))

update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 1000-300000
  update_watch_time: 1000-300000
