---
name: git-server

releases:
- name: git-server
  version: ((git_server_release_version))

instance_groups:
- name: git-server
  instances: 1
  networks: [{name: test}]
  azs: [z1]
  vm_type: test
  stemcell: xenial
  jobs:
  - release: git-server
    name: git-server
    properties:
      repositories:
      - some-repo

stemcells:
- alias: xenial
  os: ubuntu-xenial
  version: ((stemcell_version))

update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 1000-300000
  update_watch_time: 1000-300000
