resources:
- name: some-resource
  type: mock
  source: {initial_version: first-version}

jobs:
- name: simple-job
  plan:
  - get: some-resource
  - task: wait
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: {repository: busybox}
      run:
        path: sh
        args:
        - -c
        - |
          until test -f /tmp/stop-waiting; do
            echo 'waiting for /tmp/stop-waiting to exist'
            sleep 1
          done

          echo done
