resource_types:
- name: fake-resource-type
  type: mock
  source:
    mirror_self: true
    create_files:
      resource_type_secret: resource_type_secret

resources:
- name: fake-resource
  type: fake-resource-type
  source:
    create_files:
      resource_secret: resource_secret

jobs:
- name: simple-job
  plan:
  - get: fake-resource
  - task: simple-task
    params:
      SECRET: job_secret
    config:
      platform: linux

      image_resource:
        type: mock
        source:
          mirror_self: true
          create_files:
            resource_type_secret: image_resource_secret

      params:
        SECRET:

      run:
        path: sh
        args: ['-c', 'echo shhhhhh']
