---
- type: replace
  path: /instance_groups/name=web/jobs/name=web/properties/aws_ssm?
  value:
    region: ((aws_region))
    access_key: ((aws_access_key))
    secret_key: ((aws_secret_key))
    session_token: ((aws_session_token))
    pipeline_secret_template: /concourse-topgun/{{.Team}}/{{.Pipeline}}/{{.Secret}}
    team_secret_template: /concourse-topgun/{{.Team}}/{{.Secret}}
