- type: replace
  path: /instance_groups/name=web/jobs/name=web/properties/syslog?/address?
  value: ((syslog.address))

- type: replace
  path: /instance_groups/name=web/jobs/name=web/properties/syslog?/hostname?
  value: ((syslog.hostname))

- type: replace
  path: /instance_groups/name=web/jobs/name=web/properties/syslog?/transport?
  value: ((syslog.transport))

- type: replace
  path: /instance_groups/name=web/jobs/name=web/properties/syslog?/drain_interval?
  value: ((syslog.drain_interval))

- type: replace
  path: /releases/-
  value:
    name: syslog
    version: "11.3.2"
    url: "https://bosh.io/d/github.com/cloudfoundry/syslog-release?v=11.3.2"
    sha1: "64cf40d44746b50edffa78cb0e0dd6f072fee695"

- type: replace
  path: /instance_groups/name=web/jobs/name=syslog_storer?
  value:
    name: syslog_storer
    release: syslog
    properties:
      syslog:
        port: 8081
        transport: tcp


